In [33]:
import openai
from openai import OpenAI
import os
import json
import random
import glob

In [34]:
with open("_secret_key4", "r") as f:
    openai_key = f.read()
os.environ["OPENAI_API_KEY"]=openai_key#"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" # Thiemo's API key for Prashant's

In [35]:


# Define the directories
nber_dir = "../../../2_raw_data/1_nber/nber_pdf_text_all_processed_filt/"
cepr_dir = "../../../2_raw_data/2_cepr/cepr_pdf_text_all_processed_filt/"

In [36]:
import pandas as pd 
# Step 1: Read all files into DataFrames
df = pd.read_csv('../Data/Speeches/all_cb_speeches.csv',sep='\t')

In [37]:
for i in df['text'].iloc[0].split('.') :
    print(i)

Opening remarks by Dimitris Malliaropulos, Chief Economist and Director of economic analysis and research at the "GBA Session on Non-Performing Loans", organized by the London Business School at the Bank of Greece
 11/09/2019 -Speeches It is a great pleasure to welcome you today to the 2ndGBA session on Non-Performing Loans organized by the London Business School here at the Bank of Greece
 Unlike last year, where the focus of the GBA session was on the banks role and the dynamics of the financial sector, the focus this year will be more on the role of NPLs as a driver of the Greek economy dynamics and as a source of opportunity moving forward
 The steep rise in NPLs in Greece over the past decade was largely the result of the economic crisis, particularly its depth and duration
 Between 2008 and 2016, Greece lost over 25% of real GDP and the unemployment rate rose by nearly 16 percentage points
 The deterioration in the macro-economy caused serious debt-servicing problems for households and businesses
 NPLs rose substantially, weakening banks asset quality, thus making it difficult for banks to finance the real economy
 In turn, the sovereign  bank loop has exacerbated the crisis
 Since the economy is the major driver of NPL dynamics, I will first try to provide an overview of the current state of the Greek economy and the banking sector
 Then I will touch upon the main challenges for the Greek economy and the Greek banking system looking forward and explain why tackling the issue of NPLs is of high importance for the growth prospects of the economy and the health of the banking system
 Current state of economy and banking system Economy: 2019 marks the third year of economic recovery in Greece following the great recession
 Real GDP growth seems to have stabilized at around 2%, as bank financing remains scarce and expensive, not least because of the large stock of NPLs in banks balance sheets
 Nevertheless, after a weak start in the year the recovery of the Greek economy seems to be accelerating in Q2-Q3 weak start in the year, the recovery of the Greek economy seems to be accelerating in Q2-Q3, despite the global slowdown
 In particular, over the past few months, economic sentiment has increased to multiyear highs, bank funding and liquidity conditions have improved, real estate prices continued to increase and bond yields have declined significantly
 Furthermore, confidence in the banking sector has improved substantially and capital controls were fully lifted on September 1st, after being effective for 50 months
 The July 7 national elections brought a new government in office
 The new government has been elected on an ambitious reform agenda and a platform of business-friendly economic policies with a focus on accelerating reforms, speeding up privatizations, unfreezing large investment projects, attracting foreign direct investment and reducing taxation, while at the same time maintaining fiscal discipline and the agreed fiscal targets
 Short-term economic indicators suggest that the economy shows significant resilience to the global slowdown
 This is due to the positive momentum as the economy emerges from a long-lasting recession, which, to a large extent, counterbalances the negative effect from the weakening of global activity
 In particular: Economic sentiment has reached a 12-year high whereas consumer confidence has increased to a 19year high
 The recovery in the labour market continues for the fifth year, with growth rates of employment exceeding 2% y-o-y over the past three and a half years
 Revenues from tourism in real terms increased at double-digit numbers during the first six months of the year
 Second quarter 2019 GDP data suggest that growth has accelerated to 1
9% y-o-y (0
8% q-o-q) in Q2 relative to Q1, with the main drivers being net exports and public consumption
 According to forecasts by the Bank of Greece, economic activity is projected to increase by 2
3% in the second semester of 2019 and by 1
9% in the year as a whole
 Financial indicators have also improved substantially, suggesting increased confidence in the prospects of the Greek economy
 In particular: Government bond yields have declined sharply since the start of the year
 Corporate bond yields declined below 1% from more than 3% one year ago
 Deposit inflows have continued as confidence in the Greek banking system improved
 Bank credit to non-financial corporations increased in the first half of this year for the first time since 2011
 House prices have increased for six quarters in a row after suffering significant declines since the start of the crisis
 The recovery in house prices has accelerated in Q2 2019 (7
7% y-o-y)
 Banking system: The liquidity conditions of Greek banks have improved substantially, as reflected in the elimination of ELA and the overall, significant reduction in total central bank funding
 The decrease in central bank financing reflects a number of factors: First, domestic private sector deposits have been on a constant upward path over the past three years, reflecting improved confidence in the stability of the financial system
 Second, Greek banks have improved their access to the interbank market and have increased their funding from other sources such as issuance of debt securities, loan-sales and securitizations
 Third, Greek banks eligible collateral for ECB monetary policy operations has increased substantially following the upgrade of Greek banks covered bonds to investment grade
Finally, the valuation of assets held by the banks increased considerably as GGB yields declined by about 300 bps since the start of the year
 Nevertheless, Greece faces a number of challenges looking forward: Given the countrys poor demographic outlook and tight budget constraints, achieving economic growth significantly higher than the current levels of 2% in the long term is a great challenge and requires structural reforms to boost productivity and investment
 Tackling the problem of non-performing loans is critical to the health of the banking system and to its ability to finance investment and support the real economy
 Developments in Non-Performing Loans and pg challenges for Greek banks Over the past three years to mid-2019, the stock of NPLs fell by more than 30 billion from its peak of 107 billion in March 2016, largely through write-offs and sales
 Nevertheless, the stock of NPLs remains extremely high, at about 75 billion currently, equivalent to 43
6% of total outstanding loans in banks balance sheets
 Regarding their structure, more than half of NPLs are business loans, one third are mortgages and about 10% are consumer loans
Banks have agreed with the SSM a set of ambitious targets for NPL reduction: NPL ratios are to fall to 35% by the end of this year, and close to 20% by the end of 2021
 It should be noted, however, that even if these targets are met, Greek banks will have more than five times higher NPL ratios that the EU average
 Hence, it is important that a truly systemic solution, resembling an Asset Management Company, is implemented in order to complement the individual efforts of each bank to reduce NPLs
 Importantly, Greek banks have maintained satisfactory capital adequacy ratios, following three rounds of recapitalisation
 Nevertheless, legacy NPLs impose a major constraint upon Greek banks profitability, hence, their capacity to generate capital internally
 Reducing NPLs drastically is also important for financing the recovery of the Greek economy
 In fact, the high level of legacy NPLs acts as a constraint on Greek banks to extend much needed credit to the real economy
 Based on past years experience, rapid economic growth cannot be achieved unless the banking sector can finance investment at an adequate level and at a reasonable cost
 A substantial reduction of NPLs is a precondition for banks to improve their rating scores, thus allowing access to private funding at a lower cost which can be passed to companies and households in form of lower interest rates for bank credit
 Let me close with two last remarks regarding loan restructurings and reforms of the regulatory framework of NPLs: Although sales, primarily through securitizations and loan write-offs are the main drivers of the NPL reduction so far, this should not lead banks to relax their efforts to successfully restructure the loans that are still in their portfolios
 On this front, progress is rather slow and banks need to come up with improved long-term loan modification schemes so that the observed high rate of re-defaults is contained
 Finally, more work is needed to further improve the regulatory framework so as to remove bureaucratic obstacles and legal loop holes
 The new regime of primary residence protection must fit into a single and permanent legal framework for the insolvency of physical persons, while the out-ofcourt work out regime must be radically reviewed
 Thank you

In [38]:

import tqdm
import re 

import re

def split_sentences(text):
    # Common exceptions where a period does not end a sentence
    exceptions = [
        "Mr", "Mrs", "Ms", "Dr", "Prof", "Sr", "Jr", "St", "Mt", "vs",
        "etc", "e.g", "i.e", "Fig", "Inc", "Ltd", "Co", "No", "U.S", "U.K"
    ]

    # Pattern: a period followed by space and uppercase letter
    # We'll split here only if the part before the period is not in the exceptions
    pattern = re.compile(r'(?<!\w\.\w)(?<![A-Z][a-z]\.)(?<=\.)\s+(?=[A-Z])')

    # First, split using the safe pattern
    candidates = pattern.split(text)

    # Then fix any false splits by merging pieces that were wrongly split
    repaired = []
    for i, part in enumerate(candidates):
        if i == 0:
            repaired.append(part)
        else:
            prev = repaired[-1].strip()
            last_word = prev.split()[-1].rstrip('.')  # Get the last word before the split
            if last_word in exceptions or re.match(r'^[A-Z]\.?$', last_word):  # e.g., 'Dr', 'J.'
                # Merge back
                repaired[-1] = prev + ' ' + part
            else:
                repaired.append(part)

    return [s.strip() for s in repaired if s.strip()]


# Corrected regex to split sentences
#sentences = split_sentences(df['text'][0])#re.split(r'(?<!\b(?:Dr|Mr|Mrs|Ms|St))(?<!\d)\. (?=[A-Z])', all_data['text'][0])
#for i in df.index:
#    sentences = split_sentences(df['text'][i])
#    df.at[i, 'sentences'] = sentences

In [39]:
#Add a new column with the split sentences.
def add_split_sentences(df, text_col='text'):
    df['split_sentences'] = df[text_col].apply(split_sentences)
    return df

# Batch Function: Create Sentence Batches
def create_batches_from_sentences(sentences, batch_len=None,pct_of_batch=0.1):
    if batch_len==None:
        batch_len = max(int(len(sentences)*pct_of_batch),1)
        return [sentences[i:i + batch_len] for i in range(0, len(sentences), batch_len)]
    else :
        return [sentences[i:i + batch_len] for i in range(0, len(sentences), batch_len)]
        

# Master Function: Return Dictionary Per Row

def prepare_batches(df, batch_len, text_col='text',pct_of_batch=0.1):
    df = add_split_sentences(df, text_col)
    output = []

    for _, row in tqdm.tqdm(df.iterrows(),total=len(df), desc="Processing Rows"):
        batches = create_batches_from_sentences(row['split_sentences'], batch_len, pct_of_batch)
        output.append({
            'speech_id': row['speech_id'],
            'batches': batches
        })

    return output

In [40]:
from typing import List, Dict, Any, Literal
from pydantic import BaseModel, ValidationError
from openai import OpenAI
import json

# Pydantic model describing one causal relation (expanded fields)
class CauseEffect(BaseModel):
    cause_entity: str
    effect_entity: str
    relationship: str
    document_reference: str
    quantifications: str
    modulator_uncertainty: str
    modulator_temporal: str
    tense: Literal["PAST", "PRESENT", "FUTURE", "NA"]

# Build a strict JSON Schema for an object with an 'items' array of CauseEffect dicts
CAUSE_EFFECT_LIST_SCHEMA: Dict[str, Any] = {
    "name": "CauseEffectList",
    "strict": True,
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "cause_entity": {
                            "type": "string",
                            "description": (
                                "The initiating change in the economic entity, variable, event, or policy decision that sets the mechanism in motion. "
                                "Reword pronouns to what the pronouns are referring to. Be very parsimonious and include only one economic entity as the cause for each causal statement."
                                "If the sentence contains multiple causes leading to one effect, split them into separate causal statements."
                            )
                        },
                        "effect_entity": {
                            "type": "string",
                            "description": (
                                "The resulting change in the affected economic entity, variable sector or indicator as a result of the causal relationship."
                                "Reword pronouns to what the pronouns are referring to. Be very parsimonious and include only one economic entity as the effect for each causal statement "
                                "If the sentence contains multiple effects resulting from one cause, split them into separate causal statements."
                            )
                        },
                        "relationship": {
                            "type": "string",
                            "description": (
                                "Concise, precise economic logic or transmission channel explaining how the causal_entity causaly affects the effect_entity."
                            )
                        },
                        "document_reference": {
                            "type": "string",
                            "description": (
                                "The sentence which the relationship is drawn from."
                            )
                        },
                        "quantifications": {
                            "type": "string",
                            "description": (
                                "Specific numerical evidence/statistics supporting the causal claim (percentages, coefficients, magnitudes). Use 'NA' if none provided."
                            )
                        },
                        "modulator_uncertainty": {
                            "type": "string",
                            "description": (
                                "An optional modulator to the causal statement made by the speaker, composed of conditional statements like 'if', 'perhaps' etc. "
                                "It could also be a hedging statement using modals like 'can', 'could', 'might' etc or paraphrases like 'it is possible' etc. Use 'NA' if none provided."
                            )
                        },
                        "modulator_temporal": {
                            "type": "string",
                            "description": (
                                "An optional modulator to the causal statement made by the speaker about the duration of the causal relationship; quote the duration the speaker describes. Use 'NA' if none provided."
                            )
                        },
                        "tense": {
                            "type": "string",
                            "enum": ["PAST", "PRESENT", "FUTURE", "NA"],
                            "description": (
                                "A qualifier describing whether the causal relationship happened in the past [PAST], is happening in the present [PRESENT], or will take place in the future [FUTURE]. Use 'NA' if none provided."
                            )
                        }
                    },
                    "required": [
                        "cause_entity",
                        "effect_entity",
                        "relationship",
                        "document_reference",
                        "quantifications",
                        "modulator_uncertainty",
                        "modulator_temporal",
                        "tense",
                    ]
                }
            }
        },
        "required": ["items"]
    }
}

client = OpenAI()

SYSTEM_INSTRUCTIONS = (
    "You extract the main narratives from an economic speech text given by a central banker. "
    "A narrative is defined as 'a change in [X] causes a change in [Y]."
    
    "You **must** only extract explicit causal relationships stated in the text as they are made by the speaker, do not infer any additional relationships the speaker does not make."
    "Focus on economic entities, variables, events, and policy decisions mentioned in the main text, not on the notes / references of the speech."
    "Focus especially on entities relevant to central banking and macroeconomic policy such as : "
    " [inflation, unemployment, GDP, interest rates, fiscal policy, monetary policy, supply or demand shocks, "
    " financial stability, global economic conditions, labor market dynamics, commodity prices, "
    " exchange rates, trade balances, investment levels, consumption patterns, credit conditions, "
    " wage growth, productivity changes, technological innovation, demographic trends, regulatory changes and geopolitical events impacting the economy.]"
    
    "For example 'increases in government spending will increase aggregate demand' should yield"
    "cause entity : [increase in government spending]."
    "effect entity : [increase in aggregate demand]."
    "relationship : [causes]"
    "Statements of the type [A] causes [X] and [Y] should return 2 statements [A] causes [X] and [A] causes [Y]"
    "Be very precise, if a statement is of the type [A] causes [X] through [M], return [A] causes [X]  and separately [X] causes [M]."
    "Return ONLY a JSON object with an 'items' array of objects matching the schema. "
    "You are allowed to reword the entities for both cause and effect to highlight the implied changed according to the speaker if possible."
    "For instance; 'The shock from the carbon pricing implementation results in output changes' should be carbon pricing increase causes output changes."
    "( note output change does not indicate any direction absent any context )."
    "Resolve pronouns to their referents. "
    "Provide the exact sentence as document_reference."
    #"Add quantifications as concrete numbers or 'NA'. "
    "Additionally capture uncertainty modulators (hedging, conditionals, modals) or 'NA'. "
    "Also capture temporal modulators (duration qualifiers) or 'NA'. "
    "Set tense to PAST/PRESENT/FUTURE or 'NA'."
)

USER_TEMPLATE = (
    "Analyze the following sentences and extract all explicit causal relations. "
    "Focus on the economic entities present in the text, causal links between them. "
    "Resolve pronouns to concrete entities using context. "
    "Include the exact originating sentence as document_reference. "
    "Extract any numeric evidence as quantifications; otherwise use 'NA'. "
    "Identify uncertainty modulators (if, may, might, could, possible, perhaps, likely ...  but also explicit references to uncertainty, risk and ambiguity) or 'NA'. "
    "Identify temporal modulators describing duration (e.g., 'in the short term', 'over two years') or 'NA'. "
    "Classify tense as PAST, PRESENT, FUTURE; if unclear, use 'NA'.\n\n"
    "Sentences:\n{sentences}\n\n"
    "Output: JSON object only, with key 'items' containing the array."
)


def extract_batch_causality(sentences: List[str], model: str = "gpt-4o", temperature: float = 0.0) -> List[Dict[str, str]]:
    """
    Sends one batch (list of sentences) to GPT-4o and returns
    a validated list[dict] with expanded keys including  quantifications,
    modulators, and uppercase tense.

    Uses strict JSON schema via OpenAI structured outputs and validates with Pydantic.
    """
    prompt = USER_TEMPLATE.format(sentences="\n".join(f"- {s}" for s in sentences))

    resp = client.responses.create(
        model=model,
        temperature=temperature,
        input=[
            {"role": "system", "content": SYSTEM_INSTRUCTIONS},
            {"role": "user", "content": prompt},
        ],
        # Structured output via text.format (schema, name, strict)
        text={
            "format": {
                "type": "json_schema",
                "name": CAUSE_EFFECT_LIST_SCHEMA["name"],
                "schema": CAUSE_EFFECT_LIST_SCHEMA["schema"],
                "strict": CAUSE_EFFECT_LIST_SCHEMA.get("strict", True),
            }
        },
    )

    # Attempt to get JSON string/content robustly
    json_text: str | None = None

    if hasattr(resp, "output_text") and isinstance(resp.output_text, str):
        json_text = resp.output_text
    else:
        try:
            content = resp.output[0].content[0]
            if getattr(content, "type", None) == "output_json":
                json_text = content.output_json
            elif getattr(content, "type", None) == "text":
                json_text = content.text
        except Exception:
            pass

    if not json_text:
        raise RuntimeError("No textual JSON output returned from the model.")

    try:
        raw = json.loads(json_text)
    except json.JSONDecodeError as e:
        raise ValueError(f"Model did not return valid JSON: {e}\nReturned: {json_text[:500]}")

    # Accept either {items: [...]} or a bare list
    if isinstance(raw, dict) and "items" in raw and isinstance(raw["items"], list):
        raw_list = raw["items"]
    elif isinstance(raw, list):
        raw_list = raw
    else:
        raise ValueError("Expected a JSON object with 'items' array or a JSON array.")

    # Validate each item with Pydantic and normalize values
    results: List[Dict[str, str]] = []
    for item in raw_list:
        try:
            obj = CauseEffect(**item)
        except ValidationError as e:
            raise ValueError(f"Invalid item schema: {e}\nItem: {item}")

        # Normalize/clean fields
        def clean(v: str) -> str:
            return (v or "").strip()

        tense_norm = clean(obj.tense).upper()
        if tense_norm not in {"PAST", "PRESENT", "FUTURE", "NA"}:
            tense_norm = "NA"

        quant_norm = clean(obj.quantifications) or "NA"
        unc_mod_norm = clean(obj.modulator_uncertainty) or "NA"
        temp_mod_norm = clean(obj.modulator_temporal) or "NA"

        results.append(
            {
                "cause_entity": clean(obj.cause_entity),
                "effect_entity": clean(obj.effect_entity),
                "relationship": clean(obj.relationship),
                "document_reference": clean(obj.document_reference),
                "quantifications": quant_norm if quant_norm else "NA",
                "modulator_uncertainty": unc_mod_norm if unc_mod_norm else "NA",
                "modulator_temporal": temp_mod_norm if temp_mod_norm else "NA",
                "tense": tense_norm,
            }
        )

    return results


def send_batches_to_openai(
    prepared_batches: List[Dict[str, Any]],
    model: str = "gpt-4o",
    temperature: float = 0.0,
) -> List[Dict[str, Any]]:
    """
    Process the output of `prepare_batches(...)` and call GPT-4o for each batch.

    Input: list of dicts { 'speech_id': str|int, 'batches': List[List[str]] }
    Output: list of dicts { 'speech_id': ..., 'batch_results': List[List[Dict[str,str]]] }
    where each inner list is the validated list of causal dictionaries for that batch.
    """
    aggregated: List[Dict[str, Any]] = []
    for row in prepared_batches:
        speech_id = row.get("speech_id")
        batches = row.get("batches", [])

        batch_results: List[List[Dict[str, str]]] = []
        for sentences in batches:
            try:
                parsed = extract_batch_causality(sentences, model=model, temperature=temperature)
            except Exception:
                parsed = []
            batch_results.append(parsed)

        aggregated.append({
            "speech_id": speech_id,
            "batch_results": batch_results,
        })

    return aggregated

In [41]:
df

,URL,PDF,Title,Subtitle,Date,Authorname,Role,Gender,CentralBank,Country,text,text_original,Filename,Language,Source,date,speech_id
0,https://www.bankofgreece.gr/en/news-and-media/...,NaN,"Opening remarks at the ""GBA Session on Non-Per...",NaN,2019-09-11,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Opening remarks by Dimitris Malliaropulos, Chi...",NaN,grc_dimitris_malliaropulos_11_09_2019_english,English,CB websites,2019-09-11,1
1,https://www.bankofgreece.gr/en/news-and-media/...,NaN,"Opening Remarks at the IFFR Conference: ""Under...",NaN,2019-09-12,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Opening Remarks by Dimitris Malliaropulos, Chi...",NaN,grc_dimitris_malliaropulos_12_09_2019_english,English,CB websites,2019-09-12,2
2,https://www.bankofgreece.gr/enimerosi/grafeio-...,NaN,"Speech at the GetInvolved conference: ""The dec...",NaN,2019-12-13,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Speech by Dimitris Malliaropoulos, Chief Econo...",", & GetInvolved : ...",grc_dimitris_malliaropulos_13_12_2019_greek,Greek,CB websites,2019-12-13,3
3,https://www.bankofgreece.gr/en/news-and-media/...,NaN,Speech at the AHK Europa Konferenz: Remarks on...,NaN,2019-09-20,Dimitris Malliaropulos,Senior management,Male,Bank of Greece,GRC,"Speech by Dimitris Malliaropulos, Chief Econom...",NaN,grc_dimitris_malliaropulos_20_09_2019_english,English,CB websites,2019-09-20,4
4,https://www.bankofgreece.gr/en/news-and-media/...,NaN,"Speech: ""Assessing the performance and regulat...",NaN,2010-02-04,Eleni D Dendrinou-Louri,Deputy Governor,Female,Bank of Greece,GRC,"Speech of the Dep. Governor E. Louri: ""Assessi...",NaN,grc_eleni_d_dendrinou-louri_04_02_2010_english,English,CB websites,2010-02-04,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35482,NaN,https://www.boz.zm/PCF-dissemination.pdf,Speech at 2018 FPI & Investor Perceptions diss...,NaN,2018-12-05,Denny H Kalyalya,Governor,Male,Bank of Zambia,ZMB,2018 DISSEMINATION WORKSHOP ON FOREIGN PRIVATE...,NaN,zmb_pcf-dissemination,English,CB websites,2018-12-05,35483
35483,NaN,https://www.boz.zm/Speech_on_the_launch_of_the...,Official launch of the National Financial Switch,NaN,2019-06-19,Bwalya K E Ng'andu,Deputy Governor,Male,Bank of Zambia,ZMB,OFFICIAL LAUNCHING OF GOING LIVE OF THE NATION...,NaN,zmb_speech_on_the_launch_of_the_nfs_final,English,CB websites,2019-06-19,35484
35484,NaN,https://www.boz.zm/Speech.pdf,Speech on Credit Reporting Education and Aware...,NaN,2018-10-19,Denny H Kalyalya,Governor,Male,Bank of Zambia,ZMB,LAUNCH OF THE CREDIT REPORTING EDUCATION AND A...,NaN,zmb_speechoctober2018zambia,English,CB websites,2018-10-19,35485
35485,NaN,https://www.boz.zm/Talking_Notes_for_Deputy_Go...,Speech: Launch of the 2018 Digital Financial S...,NaN,2019-04-11,Bwalya K E Ng'andu,Deputy Governor,Male,Bank of Zambia,ZMB,"DR BWALYA NGANDU DEPUTY GOVERNOR - OPERATIONS,...",NaN,zmb_talking_notes_for_deputy_governor_launch_o...,English,CB websites,2019-04-11,35486
35486,NaN,https://www.boz.zm/WSD-Keynote.pdf,Keynote Speech at Launch of 2018 World Savings...,NaN,2018-10-31,Denny H Kalyalya,Governor,Male,Bank of Zambia,ZMB,LAUNCH OF THE 2018 WORLD SAVINGS DAY THEME: SA...,NaN,zmb_wsd-keynote,English,CB websites,2018-10-31,35487

In [42]:
# Prepare batches
results = prepare_batches(df, batch_len=None, text_col='text',pct_of_batch=0.3)

# Example output
for item in results:
    print(item)
    break

Processing Rows: 100%|██████████| 35487/35487 [00:10<00:00, 3486.64it/s]

{'speech_id': 1, 'batches': [['Opening remarks by Dimitris Malliaropulos, Chief Economist and Director of economic analysis and research at the "GBA Session on Non-Performing Loans", organized by the London Business School at the Bank of Greece. 11/09/2019 -Speeches It is a great pleasure to welcome you today to the 2ndGBA session on Non-Performing Loans organized by the London Business School here at the Bank of Greece.', 'Unlike last year, where the focus of the GBA session was on the banks role and the dynamics of the financial sector, the focus this year will be more on the role of NPLs as a driver of the Greek economy dynamics and as a source of opportunity moving forward.', 'The steep rise in NPLs in Greece over the past decade was largely the result of the economic crisis, particularly its depth and duration.', 'Between 2008 and 2016, Greece lost over 25% of real GDP and the unemployment rate rose by nearly 16 percentage points.', 'The deterioration in the macro-economy caused serious debt-servicing problems for households and businesses.', 'NPLs rose substantially, weakening banks asset quality, thus making it difficult for banks to finance the real economy.', 'In turn, the sovereign  bank loop has exacerbated the crisis.', 'Since the economy is the major driver of NPL dynamics, I will first try to provide an overview of the current state of the Greek economy and the banking sector.', 'Then I will touch upon the main challenges for the Greek economy and the Greek banking system looking forward and explain why tackling the issue of NPLs is of high importance for the growth prospects of the economy and the health of the banking system.', 'Current state of economy and banking system Economy: 2019 marks the third year of economic recovery in Greece following the great recession.', 'Real GDP growth seems to have stabilized at around 2%, as bank financing remains scarce and expensive, not least because of the large stock of NPLs in banks balance sheets.', 'Nevertheless, after a weak start in the year the recovery of the Greek economy seems to be accelerating in Q2-Q3 weak start in the year, the recovery of the Greek economy seems to be accelerating in Q2-Q3, despite the global slowdown.', 'In particular, over the past few months, economic sentiment has increased to multiyear highs, bank funding and liquidity conditions have improved, real estate prices continued to increase and bond yields have declined significantly.', 'Furthermore, confidence in the banking sector has improved substantially and capital controls were fully lifted on September 1st, after being effective for 50 months.', 'The July 7 national elections brought a new government in office.'], ['The new government has been elected on an ambitious reform agenda and a platform of business-friendly economic policies with a focus on accelerating reforms, speeding up privatizations, unfreezing large investment projects, attracting foreign direct investment and reducing taxation, while at the same time maintaining fiscal discipline and the agreed fiscal targets.', 'Short-term economic indicators suggest that the economy shows significant resilience to the global slowdown.', 'This is due to the positive momentum as the economy emerges from a long-lasting recession, which, to a large extent, counterbalances the negative effect from the weakening of global activity.', 'In particular: Economic sentiment has reached a 12-year high whereas consumer confidence has increased to a 19year high.', 'The recovery in the labour market continues for the fifth year, with growth rates of employment exceeding 2% y-o-y over the past three and a half years.', 'Revenues from tourism in real terms increased at double-digit numbers during the first six months of the year.', 'Second quarter 2019 GDP data suggest that growth has accelerated to 1.9% y-o-y (0.8% q-o-q) in Q2 relative to Q1, with the main drivers being net exports and public consumption.', 'According to forecasts by the Bank of Greece, economic activity is projected to increase by 2.3% in the second semester of 2019 and by 1.9% in the year as a whole.', 'Financial indicators have also improved substantially, suggesting increased confidence in the prospects of the Greek economy.', 'In particular: Government bond yields have declined sharply since the start of the year.', 'Corporate bond yields declined below 1% from more than 3% one year ago.', 'Deposit inflows have continued as confidence in the Greek banking system improved.', 'Bank credit to non-financial corporations increased in the first half of this year for the first time since 2011.', 'House prices have increased for six quarters in a row after suffering significant declines since the start of the crisis.', 'The recovery in house prices has accelerated in Q2 2019 (7.7% y-o-y).'], ['Banking system: The liquidity conditions of Greek banks have improved substantially, as reflected in the elimination of ELA and the overall, significant reduction in total central bank funding.', 'The decrease in central bank financing reflects a number of factors: First, domestic private sector deposits have been on a constant upward path over the past three years, reflecting improved confidence in the stability of the financial system.', 'Second, Greek banks have improved their access to the interbank market and have increased their funding from other sources such as issuance of debt securities, loan-sales and securitizations.', 'Third, Greek banks eligible collateral for ECB monetary policy operations has increased substantially following the upgrade of Greek banks covered bonds to investment grade.Finally, the valuation of assets held by the banks increased considerably as GGB yields declined by about 300 bps since the start of the year.', 'Nevertheless, Greece faces a number of challenges looking forward: Given the countrys poor demographic outlook and tight budget constraints, achieving economic growth significantly higher than the current levels of 2% in the long term is a great challenge and requires structural reforms to boost productivity and investment.', 'Tackling the problem of non-performing loans is critical to the health of the banking system and to its ability to finance investment and support the real economy.', 'Developments in Non-Performing Loans and pg challenges for Greek banks Over the past three years to mid-2019, the stock of NPLs fell by more than 30 billion from its peak of 107 billion in March 2016, largely through write-offs and sales.', 'Nevertheless, the stock of NPLs remains extremely high, at about 75 billion currently, equivalent to 43.6% of total outstanding loans in banks balance sheets.', 'Regarding their structure, more than half of NPLs are business loans, one third are mortgages and about 10% are consumer loans.Banks have agreed with the SSM a set of ambitious targets for NPL reduction: NPL ratios are to fall to 35% by the end of this year, and close to 20% by the end of 2021.', 'It should be noted, however, that even if these targets are met, Greek banks will have more than five times higher NPL ratios that the EU average.', 'Hence, it is important that a truly systemic solution, resembling an Asset Management Company, is implemented in order to complement the individual efforts of each bank to reduce NPLs. Importantly, Greek banks have maintained satisfactory capital adequacy ratios, following three rounds of recapitalisation.', 'Nevertheless, legacy NPLs impose a major constraint upon Greek banks profitability, hence, their capacity to generate capital internally.', 'Reducing NPLs drastically is also important for financing the recovery of the Greek economy.', 'In fact, the high level of legacy NPLs acts as a constraint on Greek banks to extend much needed credit to the real economy.', 'Based on past years experience, rapid economic growth cannot be achieved unless the banking sector can finance investment at an adequate level and at a reasonable cost.'], ['A substantial reduction of NPLs is a precondition for banks to improve their rating scores, thus allowing access to private funding at a lower cost which can be passed to companies and households in form of lower interest rates for bank credit.', 'Let me close with two last remarks regarding loan restructurings and reforms of the regulatory framework of NPLs: Although sales, primarily through securitizations and loan write-offs are the main drivers of the NPL reduction so far, this should not lead banks to relax their efforts to successfully restructure the loans that are still in their portfolios.', 'On this front, progress is rather slow and banks need to come up with improved long-term loan modification schemes so that the observed high rate of re-defaults is contained.', 'Finally, more work is needed to further improve the regulatory framework so as to remove bureaucratic obstacles and legal loop holes.', 'The new regime of primary residence protection must fit into a single and permanent legal framework for the insolvency of physical persons, while the out-ofcourt work out regime must be radically reviewed.', 'Thank you.']]}

In [43]:
boe_speeches = df[df['CentralBank']=='Bank of England']['speech_id'].tolist()

In [44]:
[i for i in results if i['speech_id']==16653]

[{'speech_id': 16653,
  'batches': [['Bank of England Page 1 Expectations, lags, and the transmission of monetary policy - speech by Catherine L. Mann Given at the Resolution Foundation 23 February 2023 Bank of England Page 2 Speech 1.',
    'Introduction Economists often reference the long and variable lags of monetary policy, first introduced by Milton Friedman in 1961.',
    'In the central banking world, 18 to 24 months is often quoted as how long it takes for changes in monetary policy to feed through to inflation, even as certainly this effect accumulates over that timeframe.',
    'Although this has by now become a sort of folk wisdom, the economic and policy environment over the past few years has prompted me to re-examine these long and variable lags.',
    'As Ive noted in numerous previous speeches1, the speed and magnitude of monetary transmission depends on the underlying structure of the economy, shocks the economy faces, and on the behaviour of financial markets, firms and households.',
    'Monetary transmission will change when the economy and the economic environment changes.',
    'Empirical estimates of the effect of monetary policy on macroeconomic aggregates are strictly speaking only valid in-sample - unless we believe that the structure of the economy has not changed in a way that would invalidate our estimates.',
    'We have been raising Bank Rate for more than a year now and by 390 basis points in total.',
    'Should we have seen more of an effect on the real economy and inflation already? Perhaps the long and variable lags are influenced by how monetary policy is transmitted through financial markets or via the expectations of participants in the real economy.',
    'Certainly the sequence of shocks that we have encountered must also matter.',
    'In the following examination of the a) data and research, b) presentation of a new financial conditions index, and c) modelling of sequential shocks and expectations in a theoretical model, I will argue that 1) financial markets have absorbed a substantial degree of the tightening to date; 2) that the sequence of shocks and embedding of inflation risks a troubling change in expectations formation via an increase in the share of backward-looking participants in the real economy; which 3) risks a worse inflation and output outcome in the longer term.',
    'This leads me to my conclusion that further tightening and sooner rather than later likely is needed to ensure the effectiveness of monetary policy to achieve the objective of 2% sustainably in the medium term. 1 See Mann, 2022a and 2022b.',
    'Bank of England Page 3 2.',
    'What is the transmission mechanism? To structure the content of this speech, let me start with the monetary transmission mechanism.',
    'The Banks Monetary Policy Committee uses a single interest rate - Bank Rate - that affects only a narrow set of financial institutions.2 How does that narrow conduit affect the behaviour of households and firms, and ultimately output and prices in the economy? Central banks rely on financial markets to pass through their policy choices in a way that is consistent with their intended consequences, alongside the role for expectations.',
    'Households and firms then react to these changed financial conditions and in light of their own expectations, which subsequently affects output and prices.',
    'Chart 1 shows a stylised representation of the main channels through which monetary policymakers expect changes in policy rates to transmit through the economy.',
    'The effectiveness of monetary policy is influenced by the functioning of these individual channels, and the interactions between them, denoted by the arrows. 2 Of course, we also have conducted Quantitative Easing and engaged in forward guidance in order to influence risk-free rates further along the yield curve but these are less direct policy tools.',
    'Our main monetary policy instrument at the moment is certainly Bank Rate.',
    'Bank of England Page 4 Source: Adapted from ECB (n.d.) Transmission mechanism of monetary policy.',
    'Factors outside of the central banks control and interactions among the channels can amplify or dampen the pass-through of any given policy choice.',
    'Id like to highlight several stages through which the transmission mechanism works in each of the following sections of this speech.',
    'The first stage comprises the transmission from a change in the policy rate through financial markets.',
    'The overall transmission mechanism is often summarised in a financial conditions index.',
    'But, as with many other cases of aggregation, it is important to look under the bonnet for where changes in the policy rate feed through to specific financial market variables, such as the exchange rate, the interest rates that firms and households face, as well as other asset prices.',
    'Changes in the policy rate dont transmit Bank of England Page 5 instantaneously though, but rather at different speeds to different financial market variables, which is one source of lags in monetary policy.',
    'The second stage of the transmission mechanism describes the pass-through of changes in financial conditions to the real economy, through the price-setting decisions of firms, wage negotiation behaviour of firms and households, as well as their spending, saving, and investment decisions.',
    'This is the stage in the transmission mechanism where lags arguably are most obvious because of agents partial attentiveness and the staggered nature of contracts, among other factors.',
    'Prices and wages are influenced by, and may spill back into demand and supply, and labour markets.',
    'But to start the transmission process, a tightening in financial conditions should mean households cut back on consumption as the cost of borrowing rises, and the opportunity cost of spending increases as saving rates rise.',
    'Firms may reduce investment, both in response to rising borrowing costs, and in anticipation of worsening demand conditions.',
    'Conditional on their pricing power and debt conditions, they may reduce prices or hold off on increasing them in order to preserve their market share, or they may even increase them to try to preserve cash flow.',
    'Expectations - that is expectations of everything: policy, prices, demand, supply - influence both financial and real-side channels but with different lags and with different degrees of forward- versus backward-looking assessments of the current data and the future.',
    'An often underappreciated feature of macroeconomics is that expectations about the future can influence the present.3 Expectations can affect wages and prices directly, possibly before demand and supply conditions in goods and labour markets have changed (Mann, 2022b).',
    'However, there are also shocks, illustrated on the right-hand side of this diagram, that are outside of the control of a central bank and can influence the key channels of the transmission mechanism.',
    'These include for instance changes in fiscal policy, trade linkages in the global economy, commodity prices, and risk preferences.',
    'In recent years, economies and central banks across the world have faced a series of these shocks, which most probably have influenced the long and variable lags - that is the effectiveness - of how changes in Bank Rate affect the real economy and inflation. 3 In this current framework, in which central banks try to explain, as best as they can, the aim of and reasoning for their policy choices, the stance of monetary policy is as much about Bank Rate today as it is about Bank Rate tomorrow.',
    'Or even, as Woodford (2005) put it: Not only do expectations about policy matter, but, at least under current conditions, very little else matters.',
    'Bank of England Page 6 3.',
    'The transmission of monetary policy through financial markets In the next few minutes, I would like to focus entirely on the first stage of the transmission mechanism, the transmission of monetary policy through financial markets.',
    'Chart 2 shows the level of Bank Rate compared to a so-called shadow rate (Wu & Xia, 2016).',
    'This shadow rate can be thought of as showing the unobserved level of the short rate that could prevail, taking into account the effects of the policy rate as well as of unconventional monetary policy tools.',
    'Since the Global Financial Crisis (GFC), central banks have employed a range of conventional und unconventional monetary policy tools.',
    'So far, I have only focused on the transmission mechanism of Bank Rate, which has been the MPCs active policy tool.',
    'The use of forward guidance and quantitative easing (QE) are unconventional tools that were essential to the easing of the monetary stance while the policy rate was restricted by its effective lower bound, but these may work through different channels.4 Chart 2: Wu-Xia shadow rate and Bank Rate Percent 94 98 02 06 10 14 18 22 Source: Wu and Xia (2020) and Bank of England.',
    'Notes: The orange dotted line constrains the shadow rate to the level of Bank Rate as suggested by the authors.',
    'Latest observation: February 2023. 4 For more information on QE and its transmission channels, see Busetto et al. (2022).',
    'Bank of England Page 7 As a first step to assess the effectiveness of the monetary transmission mechanism, a policymaker needs to understand how accommodative or tight the monetary stance is.',
    'This is not as straightforward to determine in light of the unconventional tools and the time-varying nature of r*.',
    'For a variety of reasons, the policy rate alone does not always provide an accurate read on the monetary policy stance.5 Over the last year and a half, monetary conditions have tightened significantly over a short period of time, in response to the MPCs Bank Rate increases.',
    'But, are the conditions tight? Not just the speed and size of tightening matter here, but the starting point does too.',
    'The MPC started tightening from what was a record-accommodative policy stance due to the Banks response to the Covid-19 pandemic.',
    'There is an obvious question on the interpretation of this shadow rate: Should monetary policy stance be judged by the level or the change? Which one (or both) matter for overall financial conditions and the real economy? To make an assessment on the level, you would need a relevant reference point.',
    'Is an historical average a good reference point, given the structural break present in the data around the GFC? Compared to historical average, the monetary stance is still loose.',
    'Compared to a post-GFC period, monetary stance is tighter.',
    'But research also finds that the extent to which monetary policy affects inflation depends on thresholds: that is, tightening from a loose stance has less of an effect on inflation than tightening from a tight stance (Calza and Sousa, 2005).',
    'Turning to a key part of the transmission mechanism - household debt-servicing costs.',
    'Chart 3 shows the levels of mortgage rates at 2-year and 5-year horizons, alongside maturity-matched OIS reference rates.',
    'The difference between mortgage rates (in the dotted lines) and the maturity-matched OIS rate (in solid lines) is referred to as the mortgage spread.',
    'Up until the GFC, mortgage and reference rates co-moved closely - a relationship that broke down in the financial crisis.',
    'Spreads widened as reference rates fell in response to falling policy rates and QE.',
    'But mortgage rates fell only very slowly over the next decade, and never recovered the level of pre-crisis spreads.',
    'This is evidence, at least over the sample period we are looking at, of lagged pass-through from changes in policy rates to the rates households face on their mortgages. 5 Typically, shadow rates in the literature are constrained to be near or equal to the level of the policy rate when it is above its effective lower bound (ELB).',
    'This made sense when the goal was to measure the easing effect of unconventional monetary policy.',
    'Arguably, however, also in times when the policy rate is far above the ELB, it is not a clean measure of the monetary policy stance.',
    'See for example Choi et al. (2022) who construct a less restrictive measure of the monetary policy stance for the US.',
    'Bank of England Page 8 Chart 3: Mortgage rates and OIS rates Solid lines show OIS rates, and dotted lines the maturity-matched 75% LTV mortgage rates Percent Percent _________ Source: Bank of England, Bloomberg Finance L.P, Moneyfacts and Bank calculations.',
    'Notes: For OIS data pre-2008, a Gilt-OIS spread is applied to the equivalent-maturity gilt yield data.',
    'Data is monthly until July 2018, and daily thereafter.',
    'Latest observation: 7th February 2023.',
    'Zooming in on the time since we started increasing Bank Rate, we see that mortgage rates tracked reference rates quite closely, initially, on the way up.',
    'They have also somewhat retraced their recent spike around the mini-budget turmoil of September 2022 - but not as much as have reference rates.',
    'Interest rates spiked sooner than mortgage rates did, reflecting again the lag in the pass-through from changes in reference rates to mortgage rates.',
    'It appears that pass-through from changes in risk-free rates to mortgage rates is highly state-dependent, suggesting more rapid transmission as interest rates rise and slower transmission as interest rates fall.',
    'Whereas the level of mortgages rates is higher than the trough, they are about back to pre-GFC levels, and importantly, have loosened from last autumn.',
    'Is this a tight stance for 2-year and 5-year mortgage rates? Notably, mortgage rates are definitely looser than they were last autumn, even as Bank Rate has risen further since.',
    'Bank of England Page 9 Turning now to the equity market, Chart 4 shows a decomposition of moves in equity prices into underlying components through the lens of a Dividend Discount Model.',
    'The MPCs tightening in monetary policy has had a considerable downward effect on equity prices over the last twelve months.',
    'This is the direction monetary policy makers would expect the transmission mechanism to work in a hiking cycle: higher interest rates weigh on equity prices as future earnings and cash flows are discounted using a higher discount factor.',
    'It would also make sense that higher interest rates would signal a worsening economic outlook to financial markets, which should dampen expected shareholder payouts, and potentially increase risk premia.'],
   ['Chart 4: Decomposition of equity price moves of the FTSE All-Share6 Cumulative percentage changes Percent 80 ------------------------------------------------------------------------------------------------------------------------------ Equity risk premium -80 ------------------------------------------------------------------------------------------------------------------------- Jan 22 Apr 22 Jul 22 Oct 22 Jan 23 Source: Bloomberg Finance L.P, Tradeweb, Refinitiv Eikon and l/B/E/S from LSEG, IMF WEO and Bank calculations.',
    'Latest observation: 1st February 2023.',
    'But Chart 4 shows that, in fact, shareholder payout and most notably the equity risk premium have made a positive contribution to equity prices since the beginning of last year.',
    'These have outweighed the effects of monetary policy tightening through interest rates.',
    'Shareholder payout, in aqua, captures a combination of realised cash flows to investors, and their expectations for future payout, and is often used as a proxy for market-implied views on the economic outlook.',
    'So, equity markets seem to have a reason to believe the outlook has improved since the beginning of 2022, or at least some 6 The decomposition uses the Banks Dividend Discount Model.',
    'For more information, see Dison and Rattan (2017).',
    'Bank of England Page 10 remaining elevated tail risks from the Covid period seem to have receded.',
    'This could be a result of their forward-looking nature, that inflation is expected to fall steadily this year, or reflective of the fact that long term interest rates are expected to be lower than short term ones.',
    'Either way, this chart tells an interesting story about the net effectiveness of the monetary tightening so far.',
    'The positive contribution of a falling equity risk premium implies that an improving outlook is not enough to explain equity performance.',
    'Indeed, it implies that equities have performed significantly better given what we know about interest rates and growth expectations.',
    'It seems that the MPCs tightening efforts have been in part offset by this risk premium.',
    'Moving now to how global factors affect the transmission mechanism as measured by the exchange rate.',
    'Chart 5 decomposes the moves in the Sterling-Dollar exchange rate into contributions by monetary policy, macroeconomic factors and risks.',
    'All other things being equal, a rise in UK interest rates should cause Sterling to appreciate relative to other currencies - but we see a marked depreciation instead.',
    'Chart 5: Decomposition of bilateral Sterling-Dollar exchange rate Cumulative percentage changes Source: Bloomberg Finance L.P, Refinitiv Eikon from LSEG and Bank calculations.',
    'Notes: For more information on the model see Appendix Al. Latest observation: 17th February 2023.',
    'The chart covers the entire MPC tightening cycle, and Sterling has depreciated by 10% versus the Dollar.',
    'Up until the end of 2022, the contribution of US policy and macroeconomic factors have outweighed the MPCs tightening.',
    'This in part reflects the Federal Reserve tightening, particularly at a quicker pace than the MPC, but also a better Bank of England Page 11 macroeconomic outlook in the US.',
    'More recently, the orange US bars have come off as the Fed had been expected to reduce their pace of tightening.',
    'On the other hand, the aqua bars, reflecting the pricing of UK policy and domestic macroeconomic factors, have increased, suggesting that had the MPC not tightened, the exchange rate likely would have been even weaker.',
    'Another factor weighing on Sterling, as seen through the lens of this model, is a persistent UK-specific risk premium which captures the reduced appetite for Sterling assets more broadly, that is, apparently, unrelated to direct pricing of monetary policy and future macroeconomic conditions.',
    'To summarise this section on the first stage of the transmission mechanism, Chart 6 shows a new measure of aggregate financial conditions in the UK.',
    'There are numerous such indices which all emphasise different aspects of the transmission mechanism.',
    'In my view, this measure is particularly useful as it was constructed by explicitly controlling for the non-stationarity in many underlying series, so for example should not be affected by a falling r*.',
    'Its average level should, therefore, be able to better capture a notion of neutral.',
    'That said, the distinctions among the transmission channels in the decomposition should not be considered so bright-lined given the endogeneity among the components.',
    'Chart 6: A UK financial conditions index7 Index 3 ----------------------------------------------------------------------------------------------------------------------------------_________________________________________________________________________________________________________________________________ Source: Bloomberg Finance L.P, ICE, Moneyfacts, Refinitiv Eikon from LSEG, Tradeweb and Bank calculations.',
    'Latest observation: January 2023. 7 More information can be obtained in a forthcoming Bank Underground post and in Appendix A2.',

In [45]:
import os
from typing import Iterable, List, Dict, Any

# Build JSONL lines for a given speech's batches
# Each line posts to /v1/responses with our structured schema

def _build_jsonl_lines_for_speech(
    speech_id: int | str,
    batches: Iterable[Iterable[str]],
    model: str,
    temperature: float,
) -> List[str]:
    lines: List[str] = []
    for b_idx, sentences in enumerate(batches):
        prompt = USER_TEMPLATE.format(sentences="\n".join(f"- {s}" for s in sentences))
        body = {
            "model": model,
            "temperature": temperature,
            "input": [
                {"role": "system", "content": SYSTEM_INSTRUCTIONS},
                {"role": "user", "content": prompt},
            ],
            # Structured output via text.format (schema, name, strict)
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": CAUSE_EFFECT_LIST_SCHEMA["name"],
                    "schema": CAUSE_EFFECT_LIST_SCHEMA["schema"],
                    "strict": CAUSE_EFFECT_LIST_SCHEMA.get("strict", True),
                }
            },
        }
        row = {
            "custom_id": f"speech_{speech_id}_batch_{b_idx}",
            "method": "POST",
            "url": "/v1/responses",
            "body": body,
        }
        lines.append(json.dumps(row, ensure_ascii=False))
    return lines


def create_speech_batch_and_submit(
    speech_id: int | str,
    prepared_batches: List[Dict[str, Any]],
    model: str = "gpt-4o",
    temperature: float = 0.0,
    jsonl_save_path: str | None = None,
    completion_window: str = "24h",
    metadata: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    """
    Create a Batch API job for a single `speech_id` using `/v1/responses` with structured outputs.

    Steps:
    - Build JSONL lines (one request per sentence batch)
    - Save JSONL to disk
    - Upload file with `purpose='batch'`
    - Create batch via `client.batches.create` and return summary
    """
    entry = next((r for r in prepared_batches if r.get("speech_id") == speech_id), None)
    if entry is None:
        raise ValueError(f"speech_id {speech_id} not found in prepared_batches")

    batches = entry.get("batches", [])
    lines = _build_jsonl_lines_for_speech(speech_id, batches, model=model, temperature=temperature)

    # Default save path under user_outputs if not provided
    if jsonl_save_path is None:
        os.makedirs("user_outputs/speech_runs", exist_ok=True)
        jsonl_save_path = f"user_outputs/speech_runs/speech_{speech_id}_batches.jsonl"

    with open(jsonl_save_path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")

    # Upload the JSONL file for batch processing
    uploaded = client.files.create(
        file=open(jsonl_save_path, "rb"),
        purpose="batch",
    )

    # Create the batch job
    batch = client.batches.create(
        input_file_id=uploaded.id,
        endpoint="/v1/responses",
        completion_window=completion_window,
        metadata={"speech_id": str(speech_id), **(metadata or {})},
    )

    print(
        f"Batch created. id={batch.id} status={batch.status} input_file_id={uploaded.id} "
        f"completion_window={completion_window}"
    )

    return {
        "batch_id": batch.id,
        "status": batch.status,
        "input_file_id": uploaded.id,
        "jsonl_path": jsonl_save_path,
        "completion_window": completion_window,
        "metadata": batch.metadata,
    }


# Optional: retrieve and parse batch output when it's ready

def retrieve_batch_output(batch_id: str) -> Dict[str, List[Dict[str, str]]]:
    """
    Download a completed batch's output, parse each line, and validate items using Pydantic.
    Returns a mapping: { custom_id: [ {cause_entity,...}, ... ] }.

    Prints detailed errors for non-200 responses and item validation issues.
    """
    batch = client.batches.retrieve(batch_id)
    if not getattr(batch, "output_file_id", None):
        raise RuntimeError(f"Batch {batch_id} is not yet ready or has no output_file_id. status={batch.status}")

    file_stream = client.files.content(batch.output_file_id)
    text = file_stream.text if hasattr(file_stream, "text") else file_stream.read().decode("utf-8")

    results_by_id: Dict[str, List[Dict[str, str]]] = {}
    errors_by_id: Dict[str, Dict[str, Any]] = {}
    
    for line in text.splitlines():
        if not line.strip():
            continue
        try:
            obj = json.loads(line)
        except Exception as e:
            print(f"[Batch output] Skipping invalid JSON line: {e}")
            continue

        custom_id = obj.get("custom_id") or "unknown"
        response = obj.get("response") or {}
        status_code = response.get("status_code")
        #print(response)
        # Handle HTTP-level errors reported by batch
        if isinstance(status_code, int) and status_code != 200:
            
            err_body = response.get("body", {})
            err = err_body.get("error") or {}
            info = {
                "status_code": status_code,
                "message": err.get("message"),
                "type": err.get("type"),
                "param": err.get("param"),
                "code": err.get("code"),
                "request_id": response.get("request_id"),
            }
            errors_by_id[custom_id] = info
            print(f"[Batch error] {custom_id}: status={info['status_code']} code={info['code']} param={info['param']} message={info['message']}")
            results_by_id[custom_id] = []
            continue

        # Success path: parse structured output from the response body
        body = response.get("body") if isinstance(response, dict) and "body" in response else response
        raw = None
        
        print("body",body)
        #return body

        # Try output_text
        ##if isinstance(body, dict) and isinstance(body.get("output_text"), str):
        #    try:
        #        raw_candidate = json.loads(body["output_text"])  # may be list or {items: [...]} object
        #        raw = raw_candidate
        #    except Exception:
        #        raw = []

        # Try output array with content
        if raw is None and isinstance(body, dict) and "output" in body:
            try:
                content0 = body["output"][0]["content"][0]
                if content0.get("type") == "output_text":
                    raw = content0.get("text", "[]")
                    # If output_json is a string, attempt to decode
                    if isinstance(raw, str):
                        try:
                            raw = json.loads(raw)
                        except Exception:
                            raw = []
                elif content0.get("type") == "text":
                    raw = json.loads(content0.get("text", "[]"))
            except Exception:
                raw = []
        
        #return content0,raw

        # Accept either {items: [...]} or a bare list
        if isinstance(raw, dict) and isinstance(raw.get("items"), list):
            raw_list = raw["items"]
        elif isinstance(raw, list):
            raw_list = raw
        else:
            raw_list = []

        

        #parsed_list: List[Dict[str, str]] = []
        
        #for item in raw_list:
        #    print(item)
        #    try:
        #        ce = CauseEffect(**item)
        #        #def clean(v: str) -> str: return (v or "").strip()
        #        tense_norm = #clean(ce.tense).upper()
        #        if tense_norm not in {"PAST", "PRESENT", "FUTURE", "NA"}:
        #            tense_norm = "NA"
        #        parsed_list.append({
        #            "cause_entity": clean(ce.cause_entity),
        #            "effect_entity": clean(ce.effect_entity),
        #            "relationship": clean(ce.relationship),
        #            #"document_reference": clean(ce.document_reference),
        #            "quantifications": clean(ce.quantifications) or "NA",
        #            "modulator_uncertainty": clean(ce.modulator_uncertainty) or "NA",
        #            "modulator_temporal": clean(ce.modulator_temporal) or "NA",
        #            "tense": tense_norm,
        #        })
        #    except ValidationError as e:
        #        print(f"[Item validation error] {custom_id}: {e}")
        #        continue

        results_by_id[custom_id] = raw_list

    if errors_by_id:
        print("Batch errors summary:")
        for cid, info in errors_by_id.items():
            print(
                f" - {cid}: status={info['status_code']} code={info['code']} param={info['param']} request_id={info['request_id']}\n"
                f"   message={info['message']}"
            )

    dataframe_list = []
    #print(body)
    for k,v in results_by_id.items():
        #print(v)
        df_ = pd.DataFrame(v)
        df_['custom_id'] = [k for i in range(len(df_))]
        df_['speech_id'] = [k.split('_')[1] for i in range(len(df_))]
        dataframe_list.append(df_)


    return pd.concat(dataframe_list,ignore_index=True)


from typing import Dict, Any

def check_batch_status(batch_id: str, verbose: bool = True) -> Dict[str, Any]:
    """
    Retrieve and summarize a Batch API job's status and related file ids.

    Returns a dict with keys: id, status, endpoint, input_file_id, output_file_id,
    error_file_id, completion_window, created_at, started_at, completed_at, metadata.
    """
    batch = client.batches.retrieve(batch_id)

    info: Dict[str, Any] = {
        "id": getattr(batch, "id", None),
        "status": getattr(batch, "status", None),
        "endpoint": getattr(batch, "endpoint", None),
        "input_file_id": getattr(batch, "input_file_id", None),
        "output_file_id": getattr(batch, "output_file_id", None),
        "error_file_id": getattr(batch, "error_file_id", None),
        "completion_window": getattr(batch, "completion_window", None),
        "created_at": getattr(batch, "created_at", None),
        "started_at": getattr(batch, "started_at", None),
        "completed_at": getattr(batch, "completed_at", None),
        "metadata": getattr(batch, "metadata", None),
    }

    if verbose:
        print(
            "Batch Status\n"
            f"  id: {info['id']}\n"
            f"  status: {info['status']}\n"
            f"  endpoint: {info['endpoint']}\n"
            f"  input_file_id: {info['input_file_id']}\n"
            f"  output_file_id: {info['output_file_id']}\n"
            f"  error_file_id: {info['error_file_id']}\n"
            f"  completion_window: {info['completion_window']}\n"
            f"  created_at: {info['created_at']}\n"
            f"  started_at: {info['started_at']}\n"
            f"  completed_at: {info['completed_at']}\n"
            f"  metadata: {info['metadata']}\n"
        )

    return info

# Batch submissions + status tracking helpers
import os
from typing import Iterable, List, Dict, Any
import pandas as pd

def ensure_tracking_csv(csv_path: str) -> None:
    """Ensure the tracking CSV exists with required columns."""
    if not os.path.exists(csv_path):
        df = pd.DataFrame(columns=["speech_id", "batch_id", "sent", "completed"])
        df.to_csv(csv_path, index=False)

def append_batch_rows(csv_path: str, rows: List[Dict[str, Any]]) -> pd.DataFrame:
    """Append new rows to the tracking CSV and drop duplicates by batch_id."""
    ensure_tracking_csv(csv_path)
    existing = pd.read_csv(csv_path)
    new_df = pd.DataFrame(rows)
    # Normalize types
    if "speech_id" in new_df.columns:
        new_df["speech_id"] = new_df["speech_id"].astype(str)
    if "speech_id" in existing.columns:
        existing["speech_id"] = existing["speech_id"].astype(str)
    combined = pd.concat([existing, new_df], ignore_index=True)
    if "batch_id" in combined.columns:
        combined = combined.drop_duplicates(subset=["batch_id"], keep="first")
    combined.to_csv(csv_path, index=False)
    return combined

def submit_multiple_speeches(
    speech_ids: Iterable[int | str],
    prepared_batches: List[Dict[str, Any]],
    model: str = "gpt-4o",
    temperature: float = 0.0,
    csv_path: str = "batch_submissions_Catherine_Mann.csv",
    completion_window: str = "24h",
) -> pd.DataFrame:
    """
    Submit multiple `speech_id`s in one go and track their batch_ids.

    Behavior:
    - If a `speech_id` appears in the tracking CSV with `completed=True`, skip and notify.
    - If present but not completed, re-submit and notify.
    - If not present, submit normally.

    Tracking: Appends to `csv_path` with columns: speech_id, batch_id, sent=True, completed=False.
    Returns the updated tracking DataFrame.
    """
    ensure_tracking_csv(csv_path)
    df_track = pd.read_csv(csv_path)
    # Ensure required columns exist and normalize types
    if "completed" not in df_track.columns:
        df_track["completed"] = False
    if "sent" not in df_track.columns:
        df_track["sent"] = False
    df_track["completed"] = df_track["completed"].fillna(False).astype(bool)
    df_track["sent"] = df_track["sent"].fillna(False).astype(bool)
    if "speech_id" in df_track.columns:
        df_track["speech_id"] = df_track["speech_id"].astype(str)

    rows: List[Dict[str, Any]] = []
    for sid in speech_ids:
        sid_str = str(sid)
        existing = df_track[df_track["speech_id"] == sid_str]
        if not existing.empty and existing["completed"].any():
            print(f"Skipping speech {sid_str}: already completed in tracking CSV.")
            continue
        if not existing.empty and not existing["completed"].any():
            print(f"Resubmitting speech {sid_str}: found prior submissions not completed.")
        else:
            print(f"Submitting speech {sid_str}.")
        try:
            info = create_speech_batch_and_submit(
                speech_id=sid,
                prepared_batches=prepared_batches,
                model=model,
                temperature=temperature,
                jsonl_save_path=None,
                completion_window=completion_window,
                metadata=None,
            )
            rows.append({
                "speech_id": sid_str,
                "batch_id": info.get("batch_id"),
                "sent": True,
                "completed": False,
            })
        except Exception as e:
            print(f"Failed to submit speech {sid_str}: {e}")
            continue
    updated_df = append_batch_rows(csv_path, rows)
    return updated_df

def check_all_unchecked_batches(csv_path: str = "batch_submissions_Catherine_Mann.csv", verbose: bool = True) -> pd.DataFrame:
    """
    Read tracking CSV and update `completed` for all rows where `sent==True` and `completed==False`
    by calling `check_batch_status`. Saves CSV and returns updated DataFrame.
    """
    ensure_tracking_csv(csv_path)
    df = pd.read_csv(csv_path)
    # Ensure required columns exist
    if "completed" not in df.columns:
        df["completed"] = False
    if "sent" not in df.columns:
        df["sent"] = False
    df["sent"] = df["sent"].fillna(False).astype(bool)
    df["completed"] = df["completed"].fillna(False).astype(bool)
    for idx, row in df.iterrows():
        if bool(row["sent"]) and not bool(row["completed"]):
            batch_id = row.get("batch_id")
            if not batch_id:
                continue
            try:
                info = check_batch_status(batch_id=batch_id, verbose=False)
                status = info.get("status")
                if verbose:
                    print(f"{batch_id}: status={status}")
                if status == "completed":
                    df.at[idx, "completed"] = True
            except Exception as e:
                print(f"Status check failed for {batch_id}: {e}")
                continue
    df.to_csv(csv_path, index=False)
    return df


# Retrieve outputs for all completed batches listed in the tracking CSV
from typing import Iterable, List, Dict, Any, Optional
import pandas as pd

def retrieve_multiple_submissions(
    csv_path: str = "batch_submissions_Catherine_Mann.csv",
    only_completed: bool = True,
    batch_ids: Optional[List[str]] = None,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Read the tracking CSV and run `retrieve_batch_output` for target batch_ids.

    - If `batch_ids` is None, uses CSV (completed==True when `only_completed` is True).
    - Returns a concatenated DataFrame of all retrieved outputs.
    - Adds a `batch_id` column to each returned frame.
    """
    ensure_tracking_csv(csv_path)
    df_track = pd.read_csv(csv_path)
    if "completed" not in df_track.columns:
        df_track["completed"] = False
    df_track["completed"] = df_track["completed"].fillna(False).astype(bool)
    if batch_ids is None:
        target_df = df_track[df_track["completed"]] if only_completed else df_track
        batch_ids = (
            target_df["batch_id"].dropna().astype(str).unique().tolist()
        )
    results: List[pd.DataFrame] = []
    for bid in batch_ids:
        try:
            if verbose:
                print(f"Retrieving output for {bid}...")
            out = retrieve_batch_output(bid)
            if isinstance(out, pd.DataFrame):
                out["batch_id"] = bid
                results.append(out)
            else:
                # Back-compat: if the function returns a mapping, consolidate to DataFrame
                try:
                    df_out = pd.concat([pd.DataFrame(v) for _, v in out.items()], ignore_index=True)
                    df_out["batch_id"] = bid
                    results.append(df_out)
                except Exception:
                    if verbose:
                        print(f"Unexpected output type for {bid}; skipping.")
        except Exception as e:
            print(f"Failed to retrieve {bid}: {e}")
            continue
    if not results:
        return pd.DataFrame()
    return pd.concat(results, ignore_index=True)

# Add batch IDs to tracking CSV, updating existing rows
from typing import List, Dict, Any
import pandas as pd

def add_to_batch_submissions(
    batch_ids: List[str],
    csv_path: str = "batch_submissions_Catherine_Mann.csv",
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Add or update entries in `batch_submissions_Catherine_Mann.csv` for the provided `batch_ids`.

    - Retrieves each batch via `client.batches.retrieve` to infer `speech_id` from metadata and status.
    - Updates existing rows in place (sets `sent=True`, updates `completed` based on status).
    - Appends new rows if a `batch_id` is not present.
    - Returns the updated tracking DataFrame.
    """
    ensure_tracking_csv(csv_path)
    df = pd.read_csv(csv_path)
    # Ensure required columns exist
    if "speech_id" not in df.columns:
        df["speech_id"] = ""
    if "batch_id" not in df.columns:
        df["batch_id"] = ""
    if "sent" not in df.columns:
        df["sent"] = False
    if "completed" not in df.columns:
        df["completed"] = False
    df["sent"] = df["sent"].fillna(False).astype(bool)
    df["completed"] = df["completed"].fillna(False).astype(bool)
    df["batch_id"] = df["batch_id"].astype(str)

    new_rows: List[Dict[str, Any]] = []
    for bid in batch_ids:
        bid_str = str(bid)
        try:
            batch = client.batches.retrieve(bid_str)
            metadata = getattr(batch, "metadata", {}) or {}
            speech_id = metadata.get("speech_id")
            status = getattr(batch, "status", None)
            is_completed = (status == "completed")
        except Exception as e:
            if verbose:
                print(f"Could not retrieve {bid_str}: {e}. Adding with defaults.")
            speech_id = None
            is_completed = False

        match_idxs = df.index[df["batch_id"] == bid_str].tolist()
        if match_idxs:
            for idx in match_idxs:
                if speech_id is not None:
                    df.at[idx, "speech_id"] = str(speech_id)
                df.at[idx, "sent"] = True
                df.at[idx, "completed"] = bool(is_completed)
            if verbose:
                print(f"Updated existing entry for {bid_str} (completed={is_completed}).")
        else:
            new_rows.append({
                "speech_id": str(speech_id) if speech_id is not None else "",
                "batch_id": bid_str,
                "sent": True,
                "completed": bool(is_completed),
            })
            if verbose:
                print(f"Added new entry for {bid_str} (completed={is_completed}).")

    if new_rows:
        df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)
    df.to_csv(csv_path, index=False)
    return df

### Result

In [46]:
#create_speech_batch_and_submit(speech_id=16653, 
#                               prepared_batches=results,
#                               model="gpt-4o",
#                               temperature=0.0,
#                               jsonl_save_path=None,
#                               completion_window="24h",
#                               metadata=None)


#check_batch_status(batch_id='batch_695571baf3708190896c4c14749362b6')  # Replace with actual batch ID

# Submit Catherine Mann speeches via Batch API and track status
# Filter df for Catherine Mann (robust to varying column names)

catherine_ids = df[df['Authorname']=='Catherine L Mann']['speech_id'].tolist()
CSV_OUTPUT_PATH = "batch_submissions_Catherine_Mann_detailed2.csv"
# If needed, prepare batches only for Catherine Mann's speeches (uncomment):
# results_catherine = prepare_batches(catherine_df, batch_len=None, text_col='text', pct_of_batch=0.3)
# tracking = submit_multiple_speeches(
#     speech_ids=catherine_ids,
#     prepared_batches=results_catherine,
#     model='gpt-4o',
#     temperature=0.0,
#     csv_path=CSV_OUTPUT_PATH,
#     completion_window='24h',
# )

# Submit using existing 'results' prepared earlier for the full df
tracking = submit_multiple_speeches(
    speech_ids=catherine_ids,
    prepared_batches=results,
    model='gpt-4o',
    temperature=0.0,
    csv_path=CSV_OUTPUT_PATH,
    completion_window='24h',
)
display(tracking.head())

# Optionally check all sent-but-uncompleted batches and mark completed
#updated = check_all_unchecked_batches(csv_path=CSV_OUTPUT_PATH, verbose=True)
#display(updated.head())

# Optionally check all sent-but-uncompleted batches and mark completed
updated = check_all_unchecked_batches(csv_path=CSV_OUTPUT_PATH, verbose=True)
display(updated.head())

Submitting speech 16649.
Batch created. id=batch_695bdfe6a38c8190a63f85dfb80813aa status=validating input_file_id=file-Fhbq82TQM5sHw5DAHtMQm3 completion_window=24h
Submitting speech 16650.
Batch created. id=batch_695bdfe806fc8190b95d37206d663139 status=validating input_file_id=file-9QnocZ8CvjUDy9ft3QdjuF completion_window=24h
Submitting speech 16651.
Batch created. id=batch_695bdfe90afc81908666090fd79510fa status=validating input_file_id=file-NJzKdaw8DfxQQQqEWE1Px3 completion_window=24h
Submitting speech 16652.
Batch created. id=batch_695bdfea1df88190aefc2a6a0d2aa4d1 status=validating input_file_id=file-BCK69muWBZFtY3cjX7Lr5k completion_window=24h
Submitting speech 16653.
Batch created. id=batch_695bdfeb1c7881909d67f211699a47b7 status=validating input_file_id=file-Wjmdmn5BXfHgYHzRvT4HPK completion_window=24h
Submitting speech 16654.
Batch created. id=batch_695bdfec7c0c8190b846697caa56fa8d status=validating input_file_id=file-4kRoCKyDMhqQfzYuLBVMqT completion_window=24h
Submitting speech 16655.
Batch created. id=batch_695bdfedb4508190acc81d74e37b6897 status=validating input_file_id=file-XUQ3g3b5eny5pdV8zUvtXj completion_window=24h

  speech_id                                batch_id  sent completed
0     16649  batch_695bdfe6a38c8190a63f85dfb80813aa  True     False
1     16650  batch_695bdfe806fc8190b95d37206d663139  True     False
2     16651  batch_695bdfe90afc81908666090fd79510fa  True     False
3     16652  batch_695bdfea1df88190aefc2a6a0d2aa4d1  True     False
4     16653  batch_695bdfeb1c7881909d67f211699a47b7  True     False

batch_695bdfe6a38c8190a63f85dfb80813aa: status=validating
batch_695bdfe806fc8190b95d37206d663139: status=in_progress
batch_695bdfe90afc81908666090fd79510fa: status=in_progress
batch_695bdfea1df88190aefc2a6a0d2aa4d1: status=validating
batch_695bdfeb1c7881909d67f211699a47b7: status=in_progress
batch_695bdfec7c0c8190b846697caa56fa8d: status=validating
batch_695bdfedb4508190acc81d74e37b6897: status=validating

   speech_id                                batch_id  sent  completed
0      16649  batch_695bdfe6a38c8190a63f85dfb80813aa  True      False
1      16650  batch_695bdfe806fc8190b95d37206d663139  True      False
2      16651  batch_695bdfe90afc81908666090fd79510fa  True      False
3      16652  batch_695bdfea1df88190aefc2a6a0d2aa4d1  True      False
4      16653  batch_695bdfeb1c7881909d67f211699a47b7  True      False

In [47]:
check_all_unchecked_batches(csv_path=CSV_OUTPUT_PATH, verbose=True)

batch_695bdfe6a38c8190a63f85dfb80813aa: status=validating
batch_695bdfe806fc8190b95d37206d663139: status=in_progress
batch_695bdfe90afc81908666090fd79510fa: status=in_progress
batch_695bdfea1df88190aefc2a6a0d2aa4d1: status=validating
batch_695bdfeb1c7881909d67f211699a47b7: status=in_progress
batch_695bdfec7c0c8190b846697caa56fa8d: status=validating
batch_695bdfedb4508190acc81d74e37b6897: status=in_progress

   speech_id                                batch_id  sent  completed
0      16649  batch_695bdfe6a38c8190a63f85dfb80813aa  True      False
1      16650  batch_695bdfe806fc8190b95d37206d663139  True      False
2      16651  batch_695bdfe90afc81908666090fd79510fa  True      False
3      16652  batch_695bdfea1df88190aefc2a6a0d2aa4d1  True      False
4      16653  batch_695bdfeb1c7881909d67f211699a47b7  True      False
5      16654  batch_695bdfec7c0c8190b846697caa56fa8d  True      False
6      16655  batch_695bdfedb4508190acc81d74e37b6897  True      False

In [29]:
# Example: retrieve outputs for all completed batches and preview
completed_outputs = retrieve_multiple_submissions(csv_path=CSV_OUTPUT_PATH, only_completed=True, verbose=True)
display(completed_outputs.head())

Retrieving output for batch_695a66a3679081909dffa72c9555fbdd...
body {'id': 'resp_09e1f54c65715a7400695a66ac3ea481a1b727787d10dacd66', 'object': 'response', 'created_at': 1767532204, 'status': 'completed', 'background': False, 'billing': {'payer': 'developer'}, 'completed_at': 1767532221, 'error': None, 'incomplete_details': None, 'instructions': None, 'max_output_tokens': None, 'max_tool_calls': None, 'model': 'gpt-4o-2024-08-06', 'output': [{'id': 'msg_09e1f54c65715a7400695a66ad6c8881a1bd507711efca606e', 'type': 'message', 'status': 'completed', 'content': [{'type': 'output_text', 'annotations': [], 'logprobs': [], 'text': '{"items":[{"cause_entity":"recent economic shocks","effect_entity":"uncertainties around them","relationship":"recent economic shocks create uncertainties","document_reference":"Catherine L Mann talks about the impact of recent economic shocks and the uncertainties around them.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"PRESENT"},{"cause_entity":"near-term inflationary pressures","effect_entity":"becoming embedded in domestic expectations and realisations","relationship":"near-term inflationary pressures embed in expectations and realisations","document_reference":"As I see it, the key balance of uncertainties is between near-term inflationary pressures that are becoming embedded in domestic expectations and realisations on the one hand, and on the other what is projected to be a dramatic deterioration in the real purchasing power of peoples incomes in the near and medium term.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"PRESENT"},{"cause_entity":"projected dramatic deterioration in real purchasing power","effect_entity":"deterioration in real purchasing power of people\'s incomes","relationship":"deterioration in purchasing power affects incomes","document_reference":"As I see it, the key balance of uncertainties is between near-term inflationary pressures that are becoming embedded in domestic expectations and realisations on the one hand, and on the other what is projected to be a dramatic deterioration in the real purchasing power of peoples incomes in the near and medium term.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"near and medium term","tense":"FUTURE"},{"cause_entity":"monetary policy tools","effect_entity":"short-circuit the inflationary expectations dynamic","relationship":"monetary policy tools can short-circuit inflationary expectations","document_reference":"The challenge is to deploy monetary policy tools to short-circuit the inflationary expectations dynamic now, so as to prevent inflation from remaining above target for longer, and by doing so to moderate the hit to purchasing power later on.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"now","tense":"PRESENT"},{"cause_entity":"monetary policy tools","effect_entity":"prevent inflation from remaining above target","relationship":"monetary policy tools prevent inflation from remaining above target","document_reference":"The challenge is to deploy monetary policy tools to short-circuit the inflationary expectations dynamic now, so as to prevent inflation from remaining above target for longer, and by doing so to moderate the hit to purchasing power later on.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"for longer","tense":"FUTURE"},{"cause_entity":"monetary policy tools","effect_entity":"moderate the hit to purchasing power","relationship":"monetary policy tools moderate the hit to purchasing power","document_reference":"The challenge is to deploy monetary policy tools to short-circuit the inflationary expectations dynamic now, so as to prevent inflation from remaining above target for longer, and by doing so to moderate the hit to purchasing power later on.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"later on","tense":"FUTURE"},{"cause_entity":"current inflation","effect_entity":"affecting future price inflation","relationship":"current inflation influences future price inflation","document_reference":"Uncertainties about price expectations and price realisations are particularly important, being influenced by current inflation and, in turn, affecting future price inflation.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"future","tense":"FUTURE"},{"cause_entity":"price realisations","effect_entity":"affect the evolution of real income and demand","relationship":"price realisations influence real income and demand","document_reference":"Relatedly, but its own source of uncertainty into the medium-term, is how price realisations affect the evolution of real income and demand, which in turn, will either ratify the price expectations, or not.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"medium-term","tense":"FUTURE"},{"cause_entity":"monetary policy","effect_entity":"influence inflation and output","relationship":"monetary policy affects inflation and output through financial intermediaries","document_reference":"Another uncertainty, particularly important for the medium term impact of policy, relates to the transmission mechanism from monetary policy (domestic and external) through financial intermediaries to influence inflation and output.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"medium term","tense":"FUTURE"},{"cause_entity":"shocks","effect_entity":"push inflation away from 2%","relationship":"shocks cause inflation deviation from target","document_reference":"However, the remit also recognises that shocks will push inflation away from 2%, and that appropriate monetary policy can temporarily tolerate such a deviation.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"monetary policy path","effect_entity":"cause undue volatility in economic activity","relationship":"monetary policy path can cause volatility","document_reference":"This is because the monetary policy path needed to achieve 2% at any specific point in time could cause undue volatility in economic activity.","quantifications":"NA","modulator_uncertainty":"could","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"monetary policy decisions","effect_entity":"influence expectations over future price-setting","relationship":"monetary policy decisions influence future price-setting expectations","document_reference":"But in any case, to the extent that monetary policy decisions in the short term can influence expectations over future price-setting, it can influence medium-term inflation and purchasing power, and therefore its own appropriate future stance.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"short term","tense":"FUTURE"},{"cause_entity":"monetary policy decisions","effect_entity":"influence medium-term inflation","relationship":"monetary policy decisions influence medium-term inflation","document_reference":"But in any case, to the extent that monetary policy decisions in the short term can influence expectations over future price-setting, it can influence medium-term inflation and purchasing power, and therefore its own appropriate future stance.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"medium-term","tense":"FUTURE"},{"cause_entity":"monetary policy decisions","effect_entity":"influence purchasing power","relationship":"monetary policy decisions influence purchasing power","document_reference":"But in any case, to the extent that monetary policy decisions in the short term can influence expectations over future price-setting, it can influence medium-term inflation and purchasing power, and therefore its own appropriate future stance.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"medium-term","tense":"FUTURE"},{"cause_entity":"monetary policy","effect_entity":"change financial conditions","relationship":"monetary policy changes financial conditions through intermediaries","document_reference":"Monetary policy, both by domestic and external central banks, works through financial intermediaries to change financial conditions which in turn steers aggregate demand.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"PRESENT"},{"cause_entity":"financial conditions","effect_entity":"steers aggregate demand","relationship":"financial conditions steer aggregate demand","document_reference":"Monetary policy, both by domestic and external central banks, works through financial intermediaries to change financial conditions which in turn steers aggregate demand.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"PRESENT"},{"cause_entity":"liquidity from past monetary accommodation","effect_entity":"affecting transmission of monetary policy","relationship":"liquidity from past accommodation affects policy transmission","document_reference":"With regard to the first linkage: Has the transmission of monetary policy signals to financial conditions changed, with liquidity from past monetary accommodation perhaps affecting transmission now?","quantifications":"NA","modulator_uncertainty":"perhaps","modulator_temporal":"now","tense":"PRESENT"},{"cause_entity":"previous accommodation","effect_entity":"absorbs the transmission of monetary policy","relationship":"previous accommodation absorbs policy transmission","document_reference":"To the extent that previous accommodation absorbs the transmission of monetary policy to overall financial conditions, then the signals provided by monetary policy actions to the real economy could be muted.","quantifications":"NA","modulator_uncertainty":"could","modulator_temporal":"NA","tense":"PRESENT"},{"cause_entity":"bolder monetary policy action","effect_entity":"affect financial conditions","relationship":"bolder policy action might be needed to affect conditions","document_reference":"If so, then bolder monetary policy action might be needed to affect financial conditions, to then cascade to affect real decisions.","quantifications":"NA","modulator_uncertainty":"might","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"bolder monetary policy action","effect_entity":"cascade to affect real decisions","relationship":"bolder policy action affects real decisions","document_reference":"If so, then bolder monetary policy action might be needed to affect financial conditions, to then cascade to affect real decisions.","quantifications":"NA","modulator_uncertainty":"might","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"tightness in labour and product markets","effect_entity":"downstream wage and price pressures","relationship":"tightness in markets affects wage and price pressures","document_reference":"With regard to the second linkage: Has the relationship between tightness in labour and product markets and downstream wage and price pressures changed on account of the shocks that have hit the economy?","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"PRESENT"},{"cause_entity":"monetary policy signals","effect_entity":"adjustment of the real economy","relationship":"policy signals adjust the real economy","document_reference":"Since the adjustment of the real economy to monetary policy signals is often estimated to last some 12-24 months, it is difficult to know the effects of policy in real time.","quantifications":"12-24 months","modulator_uncertainty":"NA","modulator_temporal":"12-24 months","tense":"FUTURE"},{"cause_entity":"monetary policy","effect_entity":"affects the inputs to the long-run equilibrium","relationship":"monetary policy affects long-run equilibrium inputs","document_reference":"However, to the extent that monetary policy affects the inputs to the long-run equilibrium, the terminal rate will to some degree be endogenous to the economys path to it.","quantifications":"NA","modulator_uncertainty":"to some degree","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"expectations by workers and firms for wage increases and price increases","effect_entity":"generate a domestically-driven wage-price dynamic","relationship":"expectations generate wage-price dynamic","document_reference":"Key for me was that both the DMP and the agents survey reported continued strengthening of expectations by workers and firms for wage increases and price increases, which could generate a domestically-driven wage-price dynamic with higher inflation embedded in forward-looking pricing decisions.","quantifications":"NA","modulator_uncertainty":"could","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"2021 wage settlements and price hikes","effect_entity":"inflation would remain well above target","relationship":"wage settlements and price hikes keep inflation above target","document_reference":"In my speech at the beginning of the year, I illustrated that if the 2021 wage settlements and price hikes were repeated in 2022, inflation would remain well above target for longer than initially predicted.","quantifications":"NA","modulator_uncertainty":"NA","modulator_temporal":"for longer","tense":"FUTURE"},{"cause_entity":"increase in inflation expectations","effect_entity":"significant role in wage settlements","relationship":"inflation expectations influence wage settlements","document_reference":"Therefore, even given the February projections, which showed a negative output gap from year 2 onwards, inflation expectations today likely will continue to play a significant role in wage settlements - keeping them stronger than consistent with the inflation target for longer.","quantifications":"NA","modulator_uncertainty":"likely","modulator_temporal":"for longer","tense":"FUTURE"},{"cause_entity":"firms pricing expectations","effect_entity":"recover margins eroded from input price increases and higher energy prices","relationship":"pricing expectations recover eroded margins","document_reference":"The DMP survey and agents commentary reported that firms pricing expectations for 2022 - at that time running north of 4.5% - sought to recover margins eroded from input price increases and higher energy prices in 2021.","quantifications":"north of 4.5%","modulator_uncertainty":"NA","modulator_temporal":"NA","tense":"FUTURE"},{"cause_entity":"erosion of international competition","effect_entity":"strengthen ability to pass-on or top-up import prices","relationship":"erosion of competition strengthens price pass-on ability","document_reference":"I thought that even when global goods-price inflation started to decelerate, the erosion of international competition facing UK domestic firms could strengthen their ability to pass-on, or even top-up import prices.","quantifications":"NA","modulator_uncertainty":"could","modulator_temporal":"NA","tense":"FUTURE"}]}'}], 'role': 'assistant'}], 'parallel_tool_calls': True, 'previous_response_id': None, 'prompt_cache_key': None, 'prompt_cache_retention': None, 'reasoning': {'effort': None, 'summary': None}, 'safety_identifier': None, 'service_tier': 'default', 'store': True, 'temperature': 0.0, 'text': {'format': {'type': 'json_schema', 'description': None, 'name': 'CauseEffectList', 'schema': {'type': 'object', 'additionalProperties': False, 'properties': {'items': {'type': 'array', 'items': {'type': 'object', 'additionalProperties': False, 'properties': {'cause_entity': {'type': 'string', 'description': 'The initiating change in the economic entity, variable, event, or policy decision that sets the mechanism in motion. Reword pronouns to what the pronouns are referring to. Be very parsimonious and include only one economic entity as the cause for each causal statement.If the sentence contains multiple causes leading to one effect, split them into separate causal statements.'}, 'effect_entity': {'type': 'string', 'description': 'The resulting change in the affected economic entity, variable sector or indicator as a result of the causal relationship.Reword pronouns to what the pronouns are referring to. Be very parsimonious and include only one economic entity as the effect for each causal statement If the sentence contains multiple effects resulting from one cause, split them into separate causal statements.'}, 'relationship': {'type': 'string', 'description': 'Concise, precise economic logic or transmission channel explaining how the causal_entity causaly affects the effect_entity.'}, 'document_reference': {'type': 'string', 'description': 'The sentence which the relationship is drawn from.'}, 'quantifications': {'type': 'string', 'description': "Specific numerical evidence/statistics supporting the causal claim (percentages, coefficients, magnitudes). Use 'NA' if none provided."}, 'modulator_uncertainty': {'type': 'string', 'description': "An optional modulator to the causal statement made by the speaker, composed of conditional statements like 'if', 'perhaps' etc. It could also be a hedging statement using modals like 'can', 'could', 'might' etc or paraphrases like 'it is possible' etc. Use 'NA' if none provided."}, 'modulator_temporal': {'type': 'string', 'description': "An optional modulator to the causal statement made by the speaker about the duration of the causal relationship; quote the duration the speaker describes. Use 'NA' if none provided."}, 'tense': {'type': 'string', 'enum': ['PAST', 'PRESENT', 'FUTURE', 'NA'], 'description': "A qualifier describing whether the causal relationship happened in the past [PAST], is happening in the present [PRESENT], or will take place in the future [FUTURE]. Use 'NA' if none provided."}}, 'required': ['cause_entity', 'effect_entity', 'relationship', 'document_reference', 'quantifications', 'modulator_uncertainty', 'modulator_temporal', 'tense']}}}, 'required': ['items']}, 'strict': True}, 'verbosity': 'medium'}, 'tool_choice': 'auto', 'tools': [], 'top_logprobs': 0, 'top_p': 1.0, 'truncation': 'disabled', 'usage': {'input_tokens': 3237, 'input_tokens_details': {'cached_tokens': 0}, 'output_tokens': 2799, 'output_tokens_details': {'reasoning_tokens': 0}, 'total_tokens': 6036}, 'user': None, 'metadata': {}}

,cause_entity,effect_entity,relationship,document_reference,quantifications,modulator_uncertainty,modulator_temporal,tense,custom_id,speech_id,batch_id
0,recent economic shocks,uncertainties around them,recent economic shocks create uncertainties,Catherine L Mann talks about the impact of rec...,NA,NA,NA,PRESENT,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
1,near-term inflationary pressures,becoming embedded in domestic expectations and...,near-term inflationary pressures embed in expe...,"As I see it, the key balance of uncertainties ...",NA,NA,NA,PRESENT,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
2,projected dramatic deterioration in real purch...,deterioration in real purchasing power of peop...,deterioration in purchasing power affects incomes,"As I see it, the key balance of uncertainties ...",NA,NA,near and medium term,FUTURE,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
3,monetary policy tools,short-circuit the inflationary expectations dy...,monetary policy tools can short-circuit inflat...,The challenge is to deploy monetary policy too...,NA,NA,now,PRESENT,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
4,monetary policy tools,prevent inflation from remaining above target,monetary policy tools prevent inflation from r...,The challenge is to deploy monetary policy too...,NA,NA,for longer,FUTURE,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd

In [30]:
completed_outputs

,cause_entity,effect_entity,relationship,document_reference,quantifications,modulator_uncertainty,modulator_temporal,tense,custom_id,speech_id,batch_id
0,recent economic shocks,uncertainties around them,recent economic shocks create uncertainties,Catherine L Mann talks about the impact of rec...,NA,NA,NA,PRESENT,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
1,near-term inflationary pressures,becoming embedded in domestic expectations and...,near-term inflationary pressures embed in expe...,"As I see it, the key balance of uncertainties ...",NA,NA,NA,PRESENT,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
2,projected dramatic deterioration in real purch...,deterioration in real purchasing power of peop...,deterioration in purchasing power affects incomes,"As I see it, the key balance of uncertainties ...",NA,NA,near and medium term,FUTURE,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
3,monetary policy tools,short-circuit the inflationary expectations dy...,monetary policy tools can short-circuit inflat...,The challenge is to deploy monetary policy too...,NA,NA,now,PRESENT,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
4,monetary policy tools,prevent inflation from remaining above target,monetary policy tools prevent inflation from r...,The challenge is to deploy monetary policy too...,NA,NA,for longer,FUTURE,speech_16649_batch_0,16649,batch_695a66a3679081909dffa72c9555fbdd
...,...,...,...,...,...,...,...,...,...,...,...
407,carbon price shock,affects green sector via spillover effects,Changes in carbon pricing indirectly impact th...,It is important to consider that the carbon pr...,NA,NA,NA,NA,speech_16655_batch_3,16655,batch_695a66ac6338819096be86723ff47895
408,carbon prices,raise the cost of capital of emissions-intensi...,Higher carbon prices increase operational cost...,Hengge et al. (2023) also find that carbon pri...,NA,NA,NA,PAST,speech_16655_batch_3,16655,batch_695a66ac6338819096be86723ff47895
409,contractionary monetary policy shock,output declines,Tightening monetary policy reduces economic ac...,"After a contractionary monetary policy shock, ...",NA,NA,NA,PAST,speech_16655_batch_3,16655,batch_695a66ac6338819096be86723ff47895
410,output declines,reduces the demand for emissions,"Lower output decreases industrial activity, re...","After a contractionary monetary policy shock, ...",NA,NA,NA,PAST,speech_16655_batch_3,16655,batch_695a66ac6338819096be86723ff47895
411,fall in price under the ETS,boosts output in the foreign country,"Lower carbon prices reduce costs, encouraging ...","In the foreign country, the fall in price unde...",NA,NA,NA,PRESENT,speech_16655_batch_3,16655,batch_695a66ac6338819096be86723ff47895

In [31]:

# make a unique narrative id per row grouped for each speech id
completed_outputs['speech_narrative_id'] = completed_outputs['speech_id']+ '_' + completed_outputs.groupby('speech_id').cumcount().astype(str)

In [32]:
completed_outputs.to_csv('Catherine_man_redone.csv',index=False)

In [26]:
completed_outputs['cause_entity'].value_counts()

cause_entity
monetary policy                                                         7
US tightening                                                           5
carbon taxes                                                            5
shocks                                                                  3
lending directly to NBFIs against high quality collateral               3
                                                                       ..
tighter policy stance now working through expectations                  1
firms believe monetary policy will keep Phillips curve from shifting    1
complementarity in firms price setting                                  1
monetary policy does not affect expectations formation                  1
stronger stabilisation effort from the central bank                     1
Name: count, Length: 250, dtype: int64

In [27]:
completed_outputs['effect_entity'].value_counts()

effect_entity
consumption spending support                 8
Sterling depreciation                        3
inflationary effects                         3
inflation increase                           3
positive contribution to equity prices       2
                                            ..
more intrinsic inflation persistence         1
upward-bias to wage negotiations             1
me-too-ism in firms pricing strategies       1
persistent drift higher                      1
reduced uncertainty of the climate policy    1
Name: count, Length: 287, dtype: int64

In [19]:
add_to_batch_submissions(['batch_6956b60fa168819080731e10edaa807d',
          'batch_6956b61466a4819082790d3c381fa25c',
          'batch_6956b61537f081909da7ccb610e5b200',
          'batch_6956b61700ec819099a4fb679a7c3bbf',
          'batch_6956b617fb8c81908fa5ed2308f547f6',
          "batch_6956b618e6cc8190b991ba409848446a",
          'batch_6956b61a278c8190b4842af9b41d2dfa'
          ])

Added new entry for batch_6956b60fa168819080731e10edaa807d (completed=True).
Added new entry for batch_6956b61466a4819082790d3c381fa25c (completed=True).
Added new entry for batch_6956b61537f081909da7ccb610e5b200 (completed=True).
Added new entry for batch_6956b61700ec819099a4fb679a7c3bbf (completed=True).
Added new entry for batch_6956b617fb8c81908fa5ed2308f547f6 (completed=True).
Added new entry for batch_6956b618e6cc8190b991ba409848446a (completed=True).
Added new entry for batch_6956b61a278c8190b4842af9b41d2dfa (completed=True).

   speech_id                                batch_id  sent  completed
0      16649  batch_6956d8f44df081909c8011d0627b7845  True       True
1      16650  batch_6956d8f5f28c81909766949c990cc41c  True       True
2      16651  batch_6956d8f7023c8190a99bdffe8cddd567  True       True
3      16652  batch_6956d8f88dd08190bdc03014040a547c  True       True
4      16653  batch_6956d8f9690c8190948d5033827643a4  True       True
5      16654  batch_6956d8fa93cc8190bcbcc474dcbc3b49  True       True
6      16655  batch_6956d90b121c8190b1f14c01473508d9  True       True
7      16649  batch_6956d9714e688190be18ed9b79ec69e7  True      False
8      16650  batch_6956d9728be88190833808f1da2d2ed3  True      False
9      16651  batch_6956d973c7448190addd9d5950fbeab9  True      False
10     16652  batch_6956d974be6c8190b400250d09687767  True      False
11     16653  batch_6956d9760aa88190b8c32176d6260da6  True      False
12     16654  batch_6956d976f4bc8190ae083b2a0d6ea253  True      False
13     16655  batch_6956d97820a48190b7d8da5b21e4b26f  True      False
14     16649  batch_6956b60fa168819080731e10edaa807d  True       True
15     16650  batch_6956b61466a4819082790d3c381fa25c  True       True
16     16651  batch_6956b61537f081909da7ccb610e5b200  True       True
17     16652  batch_6956b61700ec819099a4fb679a7c3bbf  True       True
18     16653  batch_6956b617fb8c81908fa5ed2308f547f6  True       True
19     16654  batch_6956b618e6cc8190b991ba409848446a  True       True
20     16655  batch_6956b61a278c8190b4842af9b41d2dfa  True       True